// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string,arg2:any,arg3:number,arg4:string,arg5:string):Promise<main.Todo>;

export function ClearTrash():Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function ExportTodos():Promise<number>;

export function GetAutoStart():Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function GetTags():Promise<Array<main.TagDef>>;

export function GetTodos():Promise<Array<main.Todo>>;

export function GetTrash():Promise<Array<main.TrashItem>>;

export function ImportTodos():Promise<main.ImportResult>;

export function PurgeTrash(arg1:number):Promise<void>;

export function ReorderTodos(arg1:Array<number>):Promise<void>;

export function RestoreTodo(arg1:number):Promise<void>;

export function SaveSettings(arg1:boolean,arg2:string):Promise<void>;

export function SaveTags(arg1:Array<main.TagDef>):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function ToggleTodo(arg1:number):Promise<main.Todo>;

export function UpdateTodo(arg1:number,arg2:string,arg3:any,arg4:number,arg5:string,arg6:string):Promise<main.Todo>;
