// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearTrash() {
  return window['go']['main']['App']['ClearTrash']();
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function ExportTodos() {
  return window['go']['main']['App']['ExportTodos']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function GetTrash() {
  return window['go']['main']['App']['GetTrash']();
}

export function ImportTodos() {
  return window['go']['main']['App']['ImportTodos']();
}

export function PurgeTrash(arg1) {
  return window['go']['main']['App']['PurgeTrash'](arg1);
}

export function ReorderTodos(arg1) {
  return window['go']['main']['App']['ReorderTodos'](arg1);
}

export function RestoreTodo(arg1) {
  return window['go']['main']['App']['RestoreTodo'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SaveTags(arg1) {
  return window['go']['main']['App']['SaveTags'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2, arg3, arg4, arg5, arg6);
}
